### PR TITLE
Fix code coverage script

### LINKED ISSUE #67: Fix code coverage shell script
The shell script (`code-coverage.sh`) included to generate a code coverage report doesn't work anymore.

### PR DESCRIPTION
**Pull request by kevin-pease**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Updates the shell script for checking the code coverage. Includes minor test value updates to prevent a blocked PR.

Fixes #67.

### :arrow_heading_down: What is the current behavior?
The script fails because it cannot find input files. 

### :new: What is the new behavior (if this is a feature change)?
A simple directory change command at the beginning of the script.

### :boom: Does this PR introduce a breaking change?
No.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines 
- [x] Relevant documentation was updated
- [x] Rebased onto current main

### CODE REVIEW

**Review by tluijken — APPROVED** [review]

File: code-coverage.sh [hunk 1]
```diff
@@ -1,3 +1,4 @@
+cd stellar_rust_sdk
```
Comment (tluijken) [inline code-coverage.sh]: Dit kan, maar is niet zo fraai. Mooiste is om `cargo test` met een manifest file aan te roepen. Mocht je relatieve paden met dependencies hebben (zoals de derive crate) dan werkt dat ook mooi. Zie onderstaande suggestie.

File: code-coverage.sh [hunk 2]
```diff
@@ -1,3 +1,4 @@
...
 CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo test
```
Comment (tluijken) [inline code-coverage.sh]:
```suggestion
CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo test --manifest-path=stellar_rust_sdk/Cargo.toml
```
Dit is ook in lijn met de github workflows voor dit project.

**Review by tluijken — CHANGES_REQUESTED** [review]

**Review by LeonardTibben — APPROVED** [review]

**Review by tluijken — APPROVED** [review]
